language: objective-c
os: osx
osx_image:
  - xcode11.3
  - xcode11.2
  - xcode10.3
env:
  - TOOLCHAIN=bazel
  - PROJECT="Catalog"
jobs:
  include:
    - name: "pod lib lint"
      osx_image: xcode11.3
      env: TOOLCHAIN=cocoapods
before_install:
  - if [ "$TOOLCHAIN" == "bazel" ]; then
      wget -O bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.2.1/bazelisk-darwin-amd64";
      chmod +x "bazelisk";
    fi
script:
  - if [ "$TOOLCHAIN" == "bazel" ]; then
      ./bazelisk test //...;
    elif [ "$TOOLCHAIN" == "cocoapods" ]; then
      pod lib lint;
    elif [ "$PROJECT" == "Catalog" ]; then
      set -o pipefail;
      pod install;
      xcodebuild build
        -workspace "MotionTransitioning.xcworkspace"
        -scheme TransitionsCatalog
        -destination "platform=iOS Simulator,name=iPhone Xs Max,OS=12.2" | xcpretty;
    fi
